- name: Install postgresql and psycopg
  ansible.builtin.apt:
    state: present
    pkg:
      - postgresql
      - python3-psycopg  # for ansible

- name: Replace everything with a new set of rules
  become: true
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ pg_cluster_ver }}/main/pg_hba.conf"
    overwrite: true  # remove preexisting rules

    # custom defaults
    rules_behavior: combine
    contype: hostssl
    address: 127.0.0.1/32
    method: trust
    comment: managed by ansible

    rules:
      - users: postgres
        databases: all
        contype: local
        method: trust
      - users: all
        databases: all

  notify: Reload postgresql

- name: Set listen_address
  community.postgresql.postgresql_alter_system:
    param: listen_address
    value: localhost
