- name: Install laptop utils
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  gather_subset:
    - "machine"
    - "!all"
    - "!env"
    - "!min"
  vars_files:
    - vars/wireguard.yml
    - vars/network.yml
    - vars/urls.yml
  vars:
    home_dir: /home/domino

  tasks:
    - name: Show Gathered Facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
      tags: never

    - name: Insert 10periodic in apt.conf.d
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/10periodic
        block: |
          APT::Periodic::Enable "1";
          APT::Periodic::MaxAge "30d";
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Verbose "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::Unattended-Upgrade "0";
        create: true
        mode: "0644"
      tags: aptconf

    - name: Insert 01norecommends in apt.conf.d
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/01norecommend
        block: |
          APT::Install-Recommends "0";
          APT::Install-Suggests "0";
        create: true
        mode: "0644"
      tags: aptconf

    - name: Install basic tools
      ansible.builtin.apt:
        pkg:
          - etckeeper
          - tuptime
          - wireguard
      tags:
        - basic
        - apt

    - name: Remove avahi and rsyslog
      ansible.builtin.apt:
        pkg:
          - avahi-daemon
          - avahi-utils
          - avahi-autoipd
          - rsyslog
          - bluetooth
          - bluez
        state: absent

    - name: Install shell, terminals and multiplexers
      ansible.builtin.apt:
        pkg:
          - zsh
          - screen
          - tmux
          - kitty
          - rxvt-unicode
      tags:
        - shell
        - apt

    - name: Install command-line tools
      ansible.builtin.apt:
        pkg:
          - psmisc
          - px
          - ack
          - ripgrep
          - gdu
          - fzf
          - mc
          - pmount
          - zip
          - unzip
          - dosfstools
          - pdftk-java
          - apt-file
          - apt-listchanges
          - debian-keyring
          - needrestart
          - deborphan
          - enca
          - secure-delete
          - tzwatch
          - man-db
          - pass
          - jq
          - man-db
      tags:
        - commandline
        - apt

    - name: Install version control tools
      ansible.builtin.apt:
        pkg:
          - git
          - vcsh
          - myrepos
          - cloc
      tags:
        - vc
        - apt

    - name: Install cups
      ansible.builtin.apt:
        pkg:
          - cups
          - cups-client
          - cups-bsd
      tags:
        - cups
        - apt

    - name: Stop and disable cups
      ansible.builtin.systemd:
        state: stopped
        enabled: false
        name: cups
      tags: cups

    - name: Install networking tools
      ansible.builtin.apt:
        pkg:
          - netcat-openbsd
          - tcpdump
          - nmap
          - wireshark
          - speedtest-cli
          - iperf3
          - ethtool
          - aircrack-ng
          - socat
          - bind9-dnsutils
      tags:
        - network
        - apt

    - name: Install mail and chat utils
      ansible.builtin.apt:
        pkg:
          - abook
          - neomutt
          - mutt
          - isync
          - notmuch
          - notmuch-mutt
          - profanity
          - bsd-mailx
          - mblaze
          - w3m
      tags:
        - mail
        - apt

    - name: Install emacs and elpa pkgs
      ansible.builtin.apt:
        pkg:
          - emacs-gtk
          - dh-elpa-helper
          - elpa-auto-complete
          - elpa-bind-key
          - elpa-clues-theme
          - elpa-concurrent
          - elpa-ctable
          - elpa-dash
          - elpa-deferred
          - elpa-diminish
          - elpa-dockerfile-mode
          - elpa-epc
          - elpa-f
          - elpa-flx
          - elpa-flx-ido
          - elpa-git-annex
          - elpa-haskell-mode
          - elpa-ht
          - elpa-jinja2-mode
          - elpa-lsp-mode
          - elpa-lv
          - elpa-markdown-mode
          - elpa-modus-themes
          - elpa-org-bullets
          - elpa-paredit
          - elpa-popup
          - elpa-projectile
          - elpa-rainbow-mode
          - elpa-s
          - elpa-smex
          - elpa-spinner
          - elpa-use-package
          - elpa-virtualenvwrapper
          - elpa-web-mode
          - elpa-which-key
          - elpa-yaml-mode
          - elpa-yasnippet
          - elpa-yasnippet-snippets
      tags:
        - emacs
        - elpa
        - apt

    - name: Install dictionaries
      ansible.builtin.apt:
        pkg:
          - aspell
          - aspell-en
          - aspell-pl
          - myspell-pl
      tags:
        - emacs
        - dict
        - apt

    - name: Install debuggers
      ansible.builtin.apt:
        pkg:
          - strace
          - ltrace
          - binwalk
      tags:
        - debug
        - apt

    - name: Install virtualization tools
      ansible.builtin.apt:
        pkg:
          - systemd-container
          - debootstrap
      tags:
        - virt
        - apt

    - name: Install media utils
      ansible.builtin.apt:
        pkg:
          - feh
          - viewnior
          - evince
          - gimp
          - gimp-gmic
          - imagemagick
          - fgallery
          - mpv
          - ffmpeg
          - mat2
          - scrot
          - zbar-tools
          - genisoimage
          - wodim
      tags:
        - media
        - apt

    - name: Install xorg
      ansible.builtin.apt:
        pkg:
          - xserver-xorg
          - xserver-xorg-core
          - xserver-xorg-input-all
          - xserver-xorg-input-libinput
          - xserver-xorg-input-synaptics
          - xserver-xorg-input-wacom
          - xserver-xorg-legacy
          - xserver-xorg-video-intel
          - x11-xserver-utils
          - x11-utils
          - x11-common
          - slim
          - xbacklight
      tags:
        - xorg
        - xmonad
        - apt

    - name: Install xmonad
      ansible.builtin.apt:
        pkg:
          - libghc-xmonad-contrib-dev
          - libghc-xmonad-contrib-doc
          - libghc-xmonad-dev
          - libghc-xmonad-doc
          - libghc-xmonad-extras-dev
          - libghc-xmonad-wallpaper-dev
          - xmonad
          - xmobar
          - suckless-tools
          - xss-lock
          - redshift
          - concalc
          - dunst
          - unclutter
          - parcellite
          - breeze-cursor-theme
          - arc-theme
          - lxappearance
      tags:
        - xmonad
        - apt

    - name: Install web browsers
      ansible.builtin.apt:
        pkg:
          - firefox-esr
          - chromium
      tags:
        - browser
        - apt

    - name: Install X11
      ansible.builtin.apt:
        pkg:
          - tigervnc-viewer
          - simple-scan
          - evolution-data-server
          - gnome-calendar
      tags:
        - vnc
        - apt

    - name: Install python
      ansible.builtin.apt:
        pkg:
          - python3
          - ipython3
          - python3-pandas
          - virtualenvwrapper
      tags:
        - python
        - apt

    - name: Install texlive
      ansible.builtin.apt:
        pkg:
          - texlive-latex-extra
          - texlive-latex-recommended
          - texlive-xetex
      tags:
        - texlive
        - apt

    - name: Install syncthing
      ansible.builtin.apt:
        pkg:
          - syncthing
      tags:
        - syncthing
        - apt

    - name: Install postfix
      ansible.builtin.apt:
        pkg:
          - postfix
          - libsasl2-2
      tags:
        - postfix
        - apt

    - name: Configure postfix
      ansible.builtin.copy:
        dest: /etc/postfix/main.cf
        content: |
          # MANAGED BY ANSIBLE
          myorigin = minik.pl
          smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
          smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
          smtpd_use_tls=yes
          smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
          smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
          relayhost = poczta.minik.pl:587
          inet_interfaces = 127.0.0.1
          smtp_use_tls = yes
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options =
          smtpd_relay_restrictions = reject_unauth_destination
        mode: "0644"
      tags: postfix

    - name: Set journald retention
      ansible.builtin.blockinfile:
        path: /etc/systemd/journald.conf.d/retention.conf
        block: |
          [Journal]
          MaxRetentionSec=1month
        create: true
        mode: "0644"
      tags: journald

    - name: Install yubikey tools
      ansible.builtin.apt:
        pkg:
          - yubikey-manager
          - libpam-yubico
      tags: yubico

    - name: Install gpg
      ansible.builtin.apt:
        pkg:
          - gpg
          - gpg-agent
          - scdaemon
          - pcscd
      tags: gpg

    - name: Setup gpg-agent
      ansible.builtin.blockinfile:
        path: "{{ home_dir }}/.gnupg/gpg-agent.conf"
        block: |
          default-cache-ttl 14400
          max-cache-ttl 14401
          enable-ssh-support
          keep-display
          #pinentry-program /usr/bin/pinentry-gtk-2
          pinentry-program /usr/bin/pinentry-curses
        create: true
        owner: domino
        mode: "0600"
      tags: gpg

    - name: Configure wireguard network
      ansible.builtin.template:
        src: "roles/wireguard/templates/wg.network.j2"
        dest: "/etc/systemd/network/{{ item }}.network"
        mode: "0644"
      loop:
        - wg0
        - wg4
        - wg5
        - wg6
      tags: wireguard

    - name: Configure wireguard netdev
      ansible.builtin.template:
        src: "roles/wireguard/templates/wg.netdev.j2"
        dest: "/etc/systemd/network/{{ item }}.netdev"
        mode: "0644"
      loop:
        - wg0
        - wg4
        - wg5
        - wg6
      tags: wireguard

    - name: Configure wlan network
      ansible.builtin.template:
        src: "roles/systemd-network/templates/wlan.network.j2"
        dest: "/etc/systemd/network/{{ iface[hostvars['localhost'].ansible_hostname] }}.network"
        mode: "0644"
      tags: systemd-network

    - name: Enable and start systemd-networkd
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: systemd-networkd
      tags: systemd-network

    - name: Stop and disable networking.service
      ansible.builtin.systemd:
        state: stopped
        enabled: false
        name: networking
      tags: systemd-network

    - name: Download signal gpg key
      ansible.builtin.get_url:
        url: "{{ signal_keyring_url }}"
        dest: /usr/share/keyrings/signal-desktop-keyring.gpg
        mode: '0644'
        checksum: sha256:efff7943ad544a2a10e10e232e695b6e7888348fb95f1deff2085fd8cab67e32
      tags: signal

    - name: Add signal apt repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: signal
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
      tags: signal

    - name: Install signal
      ansible.builtin.apt:
        pkg: signal-desktop-beta
        update_cache: true
      tags: signal

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        owner: domino
        group: domino
        state: directory
        mode: '0755'
      loop:
        - "{{ home_dir }}/Downloads"
        - "{{ home_dir }}/.local/share/fonts/truetype/iosevka"
      tags: iosevka

    - name: Download iosevka fonts
      ansible.builtin.get_url:
        url: "{{ iosevka_fonts_url }}"
        dest: "{{ home_dir }}/Downloads/iosevka.zip"
        mode: '0644'
        owner: domino
        group: domino
        checksum: sha256:29e4827a820a5ed66d7c3634e17bbb36b6308c6e92d5a801c48fc867acf97c24
      tags: iosevka

    - name: Extract iosevka.zip
      ansible.builtin.unarchive:
        src: "{{ home_dir }}/Downloads/iosevka.zip"
        dest: "{{ home_dir }}/.local/share/fonts/truetype/iosevka"
        owner: domino
        group: domino
      tags: iosevka

    - name: Install oh-my-zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ home_dir }}/.oh-my-zsh"
      become_user: domino
      tags: ohmyzsh

    - name: Add the user domino to groups
      ansible.builtin.user:
        name: domino
        shell: /bin/zsh
        groups: sudo,adm,systemd-journal,lp,lpadmin
        append: true

    - name: Reboot machine in 10 sec
      ansible.builtin.reboot:
        reboot_timeout: 10
