- name: Install laptop utils
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false

  tasks:
    - name: Insert 10periodic in apt.conf.d
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/10periodic
        block: |
          APT::Periodic::Enable "1";
          APT::Periodic::MaxAge "30d";
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Verbose "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::Unattended-Upgrade "0";
      tags: aptconf
  
    - name: Insert 01norecommends in apt.conf.d
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/01norecommend
        block: |
          APT::Install-Recommends "0";
          APT::Install-Suggests "0";
      tags: aptconf

    - name: Install basic tools
      ansible.builtin.apt:
        pkg:
          - etckeeper
          - tuptime
          - wireguard
      tags: basic

    - name: Remove avahi and rsyslog
      ansible.builtin.apt:
        pkg:
          - avahi-daemon
          - avahi-utils
          - rsyslog
        state: absent

    - name: Install shell, terminals and multiplexers 
      ansible.builtin.apt:
        pkg:
          - zsh
          - screen
          - tmux
          - kitty
          - rxvt-unicode
      tags: shell

    - name: Install command-line tools
      ansible.builtin.apt:
        pkg:
          - psmisc
          - px
          - ack
          - ripgrep
          - gdu
          - fzf
          - mc
          - pmount
          - zip
          - unzip
          - dosfstools
          - pdftk-java
          - apt-file
          - apt-listchanges
          - needrestart
          - deborphan
          - enca
          - secure-delete
          - tzwatch
      tags: commandline

    - name: Install version control tools
      ansible.builtin.apt:
        pkg:
          - git
          - vcsh
          - myrepos
          - cloc
      tags: vc
          
    - name: Install networking tools
      ansible.builtin.apt:
        pkg:
          - netcat-openbsd
          - tcpdump
          - nmap
          - wireshark
          - speedtest-cli
          - iperf3
          - ethtool
          - aircrack-ng
          - socat
          - bind9-dnsutils
      tags: network

    - name: Install mail and chat utils
      ansible.builtin.apt:
        pkg:
          - abook
          - neomutt
          - mutt
          - isync
          - notmuch
          - notmuch-mutt
          - profanity
          - bsd-mailx
          - w3m
      tags: mail

    - name: Install emacs and elpa pkgs
      ansible.builtin.apt:
        pkg:
          - emacs-gtk
          - dh-elpa-helper
          - elpa-auto-complete
          - elpa-bind-key
          - elpa-clues-theme
          - elpa-concurrent
          - elpa-ctable
          - elpa-dash
          - elpa-deferred
          - elpa-diminish
          - elpa-dockerfile-mode
          - elpa-epc
          - elpa-f
          - elpa-flx
          - elpa-flx-ido
          - elpa-git-annex
          - elpa-haskell-mode
          - elpa-ht
          - elpa-jinja2-mode
          - elpa-lsp-mode
          - elpa-lv
          - elpa-markdown-mode
          - elpa-modus-themes
          - elpa-org-bullets
          - elpa-paredit
          - elpa-popup
          - elpa-projectile
          - elpa-rainbow-mode
          - elpa-s
          - elpa-smex
          - elpa-spinner
          - elpa-use-package
          - elpa-virtualenvwrapper
          - elpa-web-mode
          - elpa-which-key
          - elpa-yaml-mode
          - elpa-yasnippet
          - elpa-yasnippet-snippets
      tags: emacs

    - name: Install dictionaries
      ansible.builtin.apt:
        pkg:
          - aspell
          - aspell-en
          - aspell-pl
          - myspell-pl
      tags:
        - emacs
        - dict

    - name: Install debuggers 
      ansible.builtin.apt:
        pkg:
          - strace
          - ltrace
          - binwalk
      tags: debug
 
    - name: Install virtualization tools
      ansible.builtin.apt:
        pkg:
          - systemd-container
          - debootstrap
      tags: virt

    - name: Install multimedia utils
      ansible.builtin.apt:
        pkg:
          - feh
          - viewnior
          - evince
          - gimp
          - gimp-gmic
          - imagemagick
          - fgallery
          - mpv
          - ffmpeg
          - mat2
          - scrot
      tags: media

    - name: Install xorg
      ansible.builtin.apt:
        pkg:
          - xserver-xorg
          - xserver-xorg-core
          - xserver-xorg-input-all
          - xserver-xorg-input-libinput
          - xserver-xorg-input-synaptics
          - xserver-xorg-input-wacom
          - xserver-xorg-legacy
          - xserver-xorg-video-intel
          - x11-xserver-utils
          - x11-utils
          - x11-common
          - slim
      tags:
        - xorg
        - xmonad

    - name: Install xmonad
      ansible.builtin.apt:
        pkg:
          - libghc-xmonad-contrib-dev
          - libghc-xmonad-contrib-doc
          - libghc-xmonad-dev
          - libghc-xmonad-doc
          - libghc-xmonad-extras-dev
          - libghc-xmonad-wallpaper-dev
          - xmonad
          - xmobar
          - suckless-tools
          - xss-lock
          - redshift
          - compton
          - concalc
          - dunst
          - unclutter
          - parcellite
      tags: xmonad

    - name: Install web browsers
      ansible.builtin.apt:
        pkg:
          - firefox-esr
          - chromium
      tags: browser
  
    - name: Install X11 tools
      ansible.builtin.apt:
        pkg:
          - tigervnc-viewer
          - simple-scan
          - evolution-data-server
          - gnome-calendar
      tags: vnc

    - name: Install python tools
      ansible.builtin.apt:
        pkg:
          - python3
          - ipython3
          - python3-pandas
      tags: python

    - name: Install TeX LaTeX XeTeX
      ansible.builtin.apt:
        pkg:
          - texlive-latex-extra
          - texlive-latex-recommended
          - texlive-xetex
      tags: texlive

    - name: Install Postfix
      ansible.builtin.apt:
        pkg:
          - postfix
          - libsasl2-2
      tags: postfix
      
    - name: Configure Postfix
      ansible.builtin.blockinfile:
        path: /etc/postfix/main.cf
        block: |
          myorigin = minik.pl
          smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
          smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
          smtpd_use_tls=yes
          smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
          smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
          relayhost = poczta.minik.pl:587
          inet_interfaces = 127.0.0.1
          smtp_use_tls = yes
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options =
          smtpd_relay_restrictions = reject_unauth_destination
      tags: postfix

    - name: Set journald retention
      ansible.builtin.blockinfile:
        path: /etc/systemd/journald.conf.d/retention.conf
        block: |
          [Journal]
          MaxRetentionSec=1month
      tags: journald
