---
- name: Run common roles
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  gather_subset:
    - "machine"
    - "!all"
    - "!env"
    - "!min"
  vars:
    username: domino
    home_dir: "/home/{{ username }}"
  roles:
    - { role: apt, tags: apt }
    - { role: grub, tags: grub }
    - { role: keyboard, tags: keyboard }
    - { role: packages, tags: packages }
    - { role: systemd, tags: systemd }
    - { role: systemd-network, tags: systemd-network }
    - { role: polkit, tags: polkit }
    - { role: zsh, tags: zsh }
    - { role: console-setup, tags: console-setup }
    - { role: gpg, tags: gpg }
    - { role: postfix, tags: postfix }
    - { role: signal, tags: signal }
    - { role: external_fonts, tags: external_fonts }
    - { role: crontab, tags: crontab }
    - { role: wireguard, tags: wireguard }
    - { role: nftables, tags: nftables }
