- name: Install cups
  ansible.builtin.apt:
    pkg:
      - cups
      - cups-client
      - cups-bsd
      - printer-driver-foo2zjs
  tags:
    - apt
    - cups
    - extra

- name: Disable now cups
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: cups
  tags:
    - cups
    - extra

- name: Add the user domino to lp groups
  ansible.builtin.user:
    name: domino
    shell: /bin/zsh
    groups: lp,lpadmin
    append: true
  tags:
    - cups
    - extra
