- name: Install cups
  ansible.builtin.apt:
    pkg:
      - cups
      - cups-client
      - cups-bsd
      - printer-driver-foo2zjs
    state: present

- name: Add the user domino to lp groups
  ansible.builtin.user:
    name: domino
    shell: /bin/zsh
    groups: lp,lpadmin
    append: true

- name: Stop and disable cups.service
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: cups
