- name: Install debuggers
  ansible.builtin.apt:
    pkg:
      - strace
      - ltrace
      - binwalk
    state: present

- name: Install virtualization tools
  ansible.builtin.apt:
    pkg:
      - systemd-container
      - debootstrap
      - docker-cli
    state: present

- name: Install python
  ansible.builtin.apt:
    pkg:
      - python3
      - ipython3
      - python3-pandas
      - python3-tabulate
      - python3-requests
      - python3-notify2
      - python3-flake8
      - python3-bs4
      - python3-lxml
      - python3-mt940
      - flake8
      - pylint
      - virtualenvwrapper
      - cloc
    state: present
