- name: Install fzf
  ansible.builtin.apt:
    name: fzf
    state: present

- name: Copy fzf key-bindings.zsh
  ansible.builtin.copy:
    src: /usr/share/doc/fzf/examples/key-bindings.zsh
    dest: "{{ home_dir }}/.config/fzf/"
    owner: domino
    group: domino
    mode: '0644'
