- name: Install basic tools
  ansible.builtin.apt:
    pkg:
      - etckeeper
      - debian-keyring
      - signing-party
      - systemd-timesyncd
  tags:
    - apt
    - basic

- name: Remove avahi and rsyslog
  ansible.builtin.apt:
    pkg:
      - avahi-daemon
      - avahi-utils
      - avahi-autoipd
      - rsyslog
      - bluetooth
      - bluez
      - isc-dhcp-client
      - isc-dhcp-common
      - ifupdown
    state: absent
  tags:
    - apt

- name: Install commandline packages
  ansible.builtin.include_tasks: commandline.yml

- name: Install networking packages
  ansible.builtin.include_tasks: networking.yml

- name: Install emacs and elpa packages
  ansible.builtin.include_tasks: emacs.yml

- name: Install and configure tuptime
  ansible.builtin.include_tasks: tuptime.yml

- name: Install graphical packages
  ansible.builtin.include_tasks: graphical.yml

- name: Install and configure fzf package
  ansible.builtin.include_tasks: fzf.yml

- name: Install cups packages
  ansible.builtin.include_tasks: cups.yml

- name: Install devel packages
  ansible.builtin.include_tasks: devel.yml

- name: Install debian packages
  ansible.builtin.include_tasks: debian.yml

- name: Install syncthing packages
  ansible.builtin.include_tasks: syncthing.yml

- name: Install yubikey packages
  ansible.builtin.include_tasks: yubikey.yml
