- name: Install postfix
  ansible.builtin.apt:
    pkg:
      - postfix
      - libsasl2-2
      - libsasl2-modules

- name: Configure postfix
  ansible.builtin.copy:
    dest: /etc/postfix/main.cf
    content: |
      # MANAGED BY ANSIBLE
      myorigin = minik.pl
      inet_interfaces = loopback-only
      relayhost = poczta.minik.pl:587
      smtp_tls_security_level = encrypt
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_sasl_security_options =
      smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
      message_size_limit = 20000000
    mode: "0644"
  tags: postfix_configure
