#!/bin/sh

# make it executable!

case $1 in
prereqs)
     echo "udev"
     exit 0
     ;;
esac

. /scripts/functions
# Begin real processing below this line

if test -x /bin/setfont && test -e /etc/console-font.psf.gz
then
    setfont /etc/console-font.psf.gz
    log_success_msg 'Set console font'
fi
