- name: Copy console-setup fonts
  ansible.builtin.copy:
    src: roles/console-setup/files/cached_Lat2-TerminusBold28x14.psf.gz
    dest: /etc/console-setup/cached_Lat2-TerminusBold28x14.psf.gz
    owner: root
    group: root
    mode: '0644'
  tags: console-setup

- name: Copy console fonts hook
  ansible.builtin.copy:
    src: roles/console-setup/files/setup-console-hook
    dest: /etc/initramfs-tools/hooks/setup-console-hook
    mode: "0744"
  tags: console-setup

- name: Copy console fonts init-top script
  ansible.builtin.copy:
    src: roles/console-setup/files/setup-console-init-top
    dest: /etc/initramfs-tools/scripts/init-top/setup-console-init-top
    mode: "0744"
  tags: console-setup
  notify: Run update-initramfs
