- name: Copy nftables
  ansible.builtin.copy:
    src: roles/nftables/files/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
    validate: /usr/sbin/nft -c -f %s
  notify: Reload nftables
  tags: nftables

- name: Enable nftables
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: nftables
  tags:
    - nftables
