- name: Show gathered facts
  ansible.builtin.debug:
    msg: "{{ ansible_facts }}"
  tags: never

- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home_dir }}/.oh-my-zsh"
    version: master
  become: true
  become_user: domino
  tags: ohmyzsh

- name: Add the user domino to groups
  ansible.builtin.user:
    name: domino
    shell: /bin/zsh
    groups: sudo,adm,systemd-journal
    append: true

- name: Set keyboard default
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: 'XKBOPTIONS="ctrl:nocaps"'
  tags: nocaps

- name: Update tuptime timer
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/tuptime-sync.timer.d/override.conf
    block: |
      [Timer]
      OnCalendar=
      OnCalendar=hourly
    create: true
    mode: "0644"
  tags: tuptime

- name: Add udev rules for ybacklight
  ansible.builtin.blockinfile:
    path: /etc/udev/rules.d/90-ybacklight.rules
    block: |
      ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
      ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
    create: true
    owner: root
    group: root
    mode: "0644"
  tags: ybacklight

- name: Add usb denylist for rainy keyboard
  ansible.builtin.blockinfile:
    path: /etc/tlp.d/01-usb_denylist.conf
    block: |
      # Bus 001 Device 002: ID 320f:5055 RDR Rainy 75
      # Bus 001 Device 003: ID 04d9:fc02 Holtek Semiconductor, Inc. USB Laser Game Mouse
      USB_DENYLIST="320f:5055 04d9:fc02"
    create: true
    owner: root
    group: root
    mode: "0644"
  tags: viia

- name: Create MAILTO env
  ansible.builtin.cron:
    name: MAILTO
    env: true
    job: "do@minik.pl"
    user: domino
  tags:
    - cron

- name: Create MAILTO env
  ansible.builtin.cron:
    name: BACKUPDIR
    env: true
    job: "{{ home_dir }}/syncthing/backup"
    user: domino
  tags:
    - cron

- name: Create a crontab to backup tuptime db
  ansible.builtin.cron:
    name: "tuptime db backup task"
    special_time: "reboot"
    job: "cp /var/lib/tuptime/tuptime.db $BACKUPDIR/$(hostname)_tuptime_$(date +%s).db"
    user: domino
  tags:
    - cron

- name: Create a crontab to /etc/hosts
  ansible.builtin.cron:
    name: "hosts backup task"
    special_time: "reboot"
    job: "cp /etc/hosts $BACKUPDIR/$(hostname)_hosts_$(date +%s)"
    user: domino
  tags:
    - cron
