- name: Configure grub timeout
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=1'
  tags:
    - grub

- name: Clear GRUB_CMDLINE_LINUX_DEFAULT
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
  tags:
    - grub

- name: Set loglevel=1 in grub cmd line
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="loglevel=1"'
  tags:
    - grub
  notify: Run update-grub
